### ISSUE TITLE
[Feature] Specify stack clone path

### ISSUE THREAD

**Issue by lighterless** [mbecker20/komodo#100]
I have multiple stacks that pull from the same repo and so currently it's cloning the same repo multiple times under `/etc/komodo/stacks/{repo}/..`

It would be nice if we could specify the stack clone path for each stack the same way we can for a repo.

<img width="814" alt="image" src="https://github.com/user-attachments/assets/354097a8-4cf4-4c16-88a4-46eacdea15b0">

**Comment by lighterless** [comment]
I can workaround this by setting up a repo and then pointing the stacks to files on the server. That works but then I lose out on the git webhooks.

**Comment by mbecker20** [comment]
If you use a shared repo for compose files, you can still setup webhook by using Procedure. The Procedure can PullRepo in the first stage, and deploy the relevant Stacks in the second stage: [https://komo.do/docs/webhooks#procedure-webhooks](https://komo.do/docs/webhooks#procedure-webhooks).

It is an common situation though, and maybe something else can help here.

**Comment by Malopieds** [comment]
> The Procedure can PullRepo in the first stage, and deploy the relevant Stacks in the second stage

I'm using a shared repo with subfolder for each service. I have a procedure webhook that works but how do you only deploy the relevant stacks? Would you have an example of doing so? My services are redeployed no matter what file is changed. Am I missing something here? Should I do something in the repos part? Thank you for your help!

**Comment by lighterless** [comment]
> If you use a shared Repo for compose files, you can still setup webhook by using Procedure. The Procedure can PullRepo in the first stage, and deploy the relevant Stacks in the second stage: https://komo.do/docs/webhooks#procedure-webhooks.
> 
> It is an common situation though, and maybe something else can help here.

I tried that too but as @Malopieds mentions, it redeploys every stack regardless of which stack in the repo is updated. 
For example I have a repo with a structure like this:

```
- services
  - actual
    - compose.yaml
  - adguardhome
    - compose.yaml
  - authelia
    - compose.yaml
  ...
```
Ideally only the stack that is updated is redeployed.

**Comment by mbecker20** [comment]
I have heard this use case a lot, when multiple stacks point to the same repo. I think the main solution here, like you mentioned, is to diff the "Deployed" files vs the "New" files, and if there aren't changes, you can skip the redeploy.

Already every Stack deploy reads the file contents it is deploying, and caches them to the database at Stack.info.deployed_contents. With this in place, doing the diff is straightforward at this point.

A new Core execution API for Stacks will help for this, called DeployStackIfChanged. I think providing this functionality can solve the problem internally for the webhook deploy case, and also gives to users the same logic to hook into inside Procedures (can just change DeployStack executions to DeployStackIfChanged executions).

**Comment by lighterless** [comment]
We are able to achieve this using a procedure and the DeployStackIfChanged action thanks to https://github.com/mbecker20/komodo/pull/117
