### ISSUE TITLE
[Feature] Containers list under sidebar

### ISSUE THREAD

**Issue by Cirx08** [mbecker20/komodo#103]
Currently there are two ways to see containers. Either filter by Stack or by Server. Neither of these options show you a full list of containers across all servers/stacks. It would ne nice to have a Containers option on the sidebar that shows a full list of all containers in the cluster.

**Comment by mbecker20** [comment]
1.15.6 Adds all containers page with link in sidebar.

**Comment by Cirx08** [comment]
I'm on version 1.15.11 but I do not see a containers option in the sidebar.

**Comment by parnic** [comment]
The Containers link only shows up in the sidebar (desktop, full-width), not the drop-down (mobile / reduced width).

<img width="658" alt="image" src="https://github.com/user-attachments/assets/5ef7ebb2-6e2c-41a3-970d-553bcb343999">

vs

<img width="762" alt="image" src="https://github.com/user-attachments/assets/5a2b7827-1634-4b4a-a2a7-0d604a2c173d">

or

<img width="762" alt="image" src="https://github.com/user-attachments/assets/a72b5e7d-4a7c-459b-9a50-c4793b1735dc">
