### ISSUE TITLE
[Feature] Run commands/scripts on sync before deploy

### ISSUE THREAD

**Issue by mercxry** [mbecker20/komodo#104]
Hello, let me start by saying that I wanted to build a similar project for a long time, but unfortunately didn't have enough time to do it, so thank you for building this!

One of the main problems I have with full adoption of this, is that it doesn't seem to be able to run commands/scripts after pulling and before deploying, for example I would like to decrypt some `.env`s with SOPS and build some templated configs before it deploys the stack.
A workaround would be to have a service receive the webhook from Github, send the sync webhook to komodo then do these actions and finally send the deploy webhook to komodo, but I think this feature would be great to have natively in komodo.

Is this something you would like to see in this project? If so I'd love to contribute it with a PR as soon as I have some free time 😄

**Comment by Fane447** [comment]
Was about to request this too. 

I saw under the Builds section there is a Pre Build section to run custom commands, something like this could be nice to have in the stacks section.

The use I would like, is for me to be able to store my secrets in 1password and then in the Komodo side of environment, have the variables listed like so

OPENAI_API_KEY=op://vault/openapi/key

And then get to Komodo create the .env file with that value, then a custom pre-deploy command could be ran vs that .env file to replace the op:// sections with the actual secrets.

**Comment by mbecker20** [comment]
Hi, `1.15.3` adds the Stack `Pre Deploy` command, you can go ahead and try it out. Let me know if you have any thoughts.
