### ISSUE TITLE
Komodo with Mongo docker deployment in v1.15.0

### ISSUE THREAD

**Issue by parnic** [mbecker20/komodo#105]
My Komodo install went into a restart loop when Watchtower updated it to v1.15.0. It was timing out attempting to connect to the database server which the timeout log reported as `localhost:27017` even though I had `KOMODO_MONGO_ADDRESS` set to `mongo:27017`. From looking at the updated docs today, it seems that `KOMODO_MONGO_*` has been renamed to `KOMODO_DATABASE_*`. This is a reasonable change if the variable is meant to support multiple backing database types, but it is a breaking change that doesn't appear to be called out in the release notes, and I assume there's no compatibility layer to allow the old name(s) to work.

So: was this change intentional? Was there a way to know about it ahead of time or should the release notes be updated, at least? Semver would usually call for a breaking change to be a new major version bump.

I see the change came from https://github.com/mbecker20/komodo/pull/90/commits/8dbd8fe035364700067d14782552d538c9b3b4c0 which appears to have attempted to put aliases in place, but those aliases don't seem to be working.

If https://github.com/mbecker20/komodo/commit/0600276b43f4b87e72b2e782b29a6305292fd4d3 is the fix for this, can we get that pushed out quickly? :)

**Comment by parnic** [comment]
Looks like https://github.com/mbecker20/komodo/commit/0600276b43f4b87e72b2e782b29a6305292fd4d3 was the fix and v1.15.1 is deployed now. 👍

**Comment by mbecker20** [comment]
Yeah sorry about that, the intention was backwards compatibility, just had to get that patch out.
