### ISSUE TITLE
OIDC not working

### ISSUE THREAD

**Issue by jochem3k** [mbecker20/komodo#106]
After setting up OIDC through Authentik I get unclickable login button:
![image](https://github.com/user-attachments/assets/8170b097-1ffe-4de3-86d0-dd89ca9afdb3)

**Comment by mbecker20** [comment]
Can you check the `core` service logs?

**Comment by jochem3k** [comment]
komodo_core       | Error: task 5 panicked
komodo_core       | thread 'tokio-runtime-worker' panicked at bin/core/src/auth/oidc/client.rs:66:4:
komodo_core       | called `Result::unwrap()` on an `Err` value: Failed to init default OIDC client
komodo_core       | 
komodo_core       | Caused by:
komodo_core       |     0: Failed to get OIDC /.well-known/openid-configuration
komodo_core       |     1: Validation error: unexpected issuer URI `https://OIDC-provider.tld/application/o/komodo/` (expected `https://OIDC-provider.tld/application/o/komodo`)
komodo_core       | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
komodo_core exited with code 1

**Comment by mbecker20** [comment]
Can you try updating to `1.15.2`? And ensure your `KOMODO_OIDC_PROVIDER` doesn't end with trailing slash, some providers want it there and some don't.

**Comment by jochem3k** [comment]
After reading the release notes to 1.15.1 I *added* the trailing slash to the KOMODO_OIDC_PROVIDER. 
It works now, thank you :)
