### ISSUE TITLE
Komodo Periphery as docker container, self pauses or self stops

### ISSUE THREAD

**Issue by metril** [mbecker20/komodo#107]
When running the Komodo Periphery as a docker container, the container is susceptible to being paused or stopped. This means that pausing or stopping then disconnects the server from the Komodo Manager until you login to the server and start or unpause the periphery container.

**Comment by mbecker20** [comment]
Do you have logs from this event? This is definitely not normal behavior for Periphery. Could some other part of your setup be stopping the container if you log out for a certain amount of time?

**Comment by metril** [comment]
It's not that periphery is stopping by itself. If you go to the Komodo manager and you tell it to pause or stop docker containers and if periphery itself is running as a container, then it too is paused or stopped.

**Comment by mbecker20** [comment]
Hm, yeah running "StopAllContainers" on the Server running periphery WILL stop periphery as well. I see what you mean. Under the Server `Docker` tab, you can click into the containers and control them individually. Some bulk actions (ie selecting multiple containers in the table and stopping them all) would be nice here.

**Comment by metril** [comment]
I think the StopAllContainers or PauseAllContainers should ignore the Periphery container. This is like how Portainer does not show you the Portainer Agent container in the GUI unless you change some settings.

**Comment by mbecker20** [comment]
Ok, I think I have a solution here. A label  like`komodo.periphery: anything`, and the server `StopAllContainers` and related api can skip containers with this label. And I'll add this label to all the documentation, eg compose files.

**Comment by mbecker20** [comment]
The `StopAllContainers` (and all other `Server` level container actions) will now ignore containers with the label `komodo.skip` set.

**Comment by MRobi1** [comment]
Is this coming to `stack` level actions as well?

Pressing Stop on the stack page also stops the periphery container. And because it's stopped, Komodo throws a Stop Stack task error

![Image](https://github.com/user-attachments/assets/0c35e71c-9bda-45a0-99aa-bb8b712c2787)

![Image](https://github.com/user-attachments/assets/eee952f3-dc96-4ae4-a482-3a4ed098fb3c)

```
ERROR: failed at request to periphery

TRACE:
	1: error sending request for url (https://X.X.X.X:8120/)
	2: client error (SendRequest)
	3: connection error
	4: peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof
```

If stopping periphery is the intended result since it's bringing down the entire stack, I'd recommend not having it throw a task error.

**Comment by ilkersigirci** [comment]
@mbecker20 I am using the latest version. Even though I have added `komodo.skip` to the periphery container and some other containers, it seems to have no effect on my end. I am using `Stacks` with `File on the server` option btw
