### ISSUE TITLE
Random link to "www.tradingview.com" on the Komodo Manager

### ISSUE THREAD

**Issue by metril** [mbecker20/komodo#108]
On the Historical charts, there is a logo that appears. Clicking this logo takes you to trading website. What is this?
<img width="349" alt="Screenshot 2024-10-07 at 9 59 06 PM" src="https://github.com/user-attachments/assets/35603107-caef-421b-878b-01ec0876b883">

**Comment by mbecker20** [comment]
Its using this open source npm packaage for the system stats charts: [https://github.com/tradingview/lightweight-charts](https://github.com/tradingview/lightweight-charts). Tradingview is the creator of this library, It's unfortunate they started embedding the link in the chart, they didn't used to do this. It comes from finance but can chart any data, and looks high quality, its hard to find this. But I get their logo / link is kind of off putting, it would be better to use another project for the charts.

**Comment by metril** [comment]
It is very off putting. Does it make sense to roll back the library to a previous version and perhaps find an alternative?

**Comment by mbecker20** [comment]
1.15.6+ now uses react charts [https://react-charts.tanstack.com/](https://react-charts.tanstack.com/)
