### ISSUE TITLE
feature: add timestamps to "log" tab in the console

### ISSUE THREAD

**Issue by LawMixer** [mbecker20/komodo#110]
To put it simply, we could display the time in the users' local time zone, or we could have it set to the UTC time zone (or the default of the server provided) 

Example:
[00:00:00 MM/DD/YYYY]  Console Output

To the argument this brings up, "why can't you program that in yourself", 

This is a possibly, but to be doing it for every single application you put on the server - it'll become tedious and if for whatever reason somebody wants to switch off of Komodo (which I don't know why somebody would, come on now) they would have to change it again to allow for that other panel they went back to.

**Comment by mbecker20** [comment]
done in 1.15.4

**Comment by LawMixer** [comment]
Currently, this is how it looks:
``2024-10-10T11:16:30.528671467Z [ROBLOX AUDIT LOG]: Server timed out: `` 

which isn't really readable - could we maybe do it to like ``[00:00:00 MM/DD/YYYY] `` if need be, we can always let the user choose!

Thanks for accepting my feature request and implementing it so quick!!

**Comment by mbecker20** [comment]
The timestamps come from Docker directly using --timestamp, I don't have a way to format them: https://docs.docker.com/reference/cli/docker/container/logs/
