### ISSUE TITLE
Cannot edit user or delete

### ISSUE THREAD

**Issue by Joly0** [mbecker20/komodo#115]
Hey, i noticed, i cant edit the password of a user (or even my own) and i cannot delete users?
Is there something that i am missing?

**Comment by mbecker20** [comment]
Hi, you are correct, it can't edit your users password or delete users (can disable users to cut off access). Also see this: https://github.com/mbecker20/komodo/blob/8582bc92da5ad2bf5fcff12478f922c29c30e19a/config/core.config.toml#L75

It's a good point though, I can add both of these functionalities shortly.

**Comment by Joly0** [comment]
Ok, thank you. Would definitely be helpful to change my password or remove users.
I want to ditch portainer and for testing only i setup a weak password which i cant change now easily

**Comment by mbecker20** [comment]
Done in 1.15.5
