### ISSUE TITLE
[Question] Update Komodo periphery ?

### ISSUE THREAD

**Issue by Nonobis** [mbecker20/komodo#120]
Hello,

How to auto update "Komodo Periphery' if installed via sh script ?
Do i need to execute the script on all remote device ?

Thanks

**Comment by mbecker20** [comment]
Hi, Komodo doesn't come with inbuilt solution for upgrading Periphery currently.

But the script is fine to run over and over, it won't change your configs if they are already set. So you can run the install sh every day with something like CRON job. Or you can setup some other automation tool like Puppet to update the binary.
