### ISSUE TITLE
Authentik / OIDC Redirect URI Error

### ISSUE THREAD

**Issue by cratedev** [mbecker20/komodo#121]
Probably user error but I've read through the docs and I can't seem to figure this one out.

Using authentik 2024.8
Using komodo 1.15.7

In my compose:

```
      KOMODO_OIDC_ENABLED: true
      KOMODO_OIDC_PROVIDER: "https://authentik.domain.dev/application/o/komodo/"
      KOMODO_OIDC_CLIENT_ID: "clientid"
      KOMODO_OIDC_CLIENT_SECRET: "clientsecret"
```

In Authentik Providers:
```
Redirect URIs
https://komodo.domain.dev/auth/oidc/callback

OpenID Configuration Issuer
https://authentik.domain.dev/application/o/komodo/
```

Going to komodo.domain.dev and clicking OIDC, I get:
```
Redirect URI Error
The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).
```

In the address bar the URI redirect seems correct:
```
https://authentik.domain.dev/application/o/authorize/?response_type=code&client_id=clientid&state=xxx&code_challenge=D9vk-WaX7iKovA-xxx&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fkomodo.domain.dev%2Fauth%2Foidc%2Fcallback&scope=openid+openid+email&nonce=YY-EzCCJX2p3NZpoD-6Bng
```

Am I doing something obviously wrong?

**Comment by metril** [comment]
Check your Authentik OIDC configuration. The redirect URI you put in Authentik is wrong.

**Comment by cratedev** [comment]
> Check your Authentik OIDC configuration. The redirect URI you put in Authentik is wrong.

Looks correct from the [docs](https://komo.do/docs/setup/advanced)
`<KOMODO_HOST>/auth/oidc/callback for OIDC.`

**Comment by metril** [comment]
Can you paste a screenshot of your Authentik OIDC configuration?

**Comment by cratedev** [comment]
> Can you paste a screenshot of your Authentik OIDC configuration?

![Uploading 24.10.13-17:31:47.png…]()

**Comment by cratedev** [comment]
Redeployed my containers a few times and now it works. Dunno what the deal was, but it's working now.
