### ISSUE TITLE
Unpausing a paused containers does not work

### ISSUE THREAD

**Issue by metril** [mbecker20/komodo#122]
Unpausing a paused container using the web interface results in komodo trying to start the container and errors. Unpausing a container should "unpause" and not "start" the container.

Here, I clicked unpause, but you can see that it tried to "start" the container instead.
![image](https://github.com/user-attachments/assets/b4281c2a-9ecf-42ec-8604-2e6740498036)

**Comment by mbecker20** [comment]
Hi I just released 1.15.8 which fixes this issue
