### ISSUE TITLE
login credentials for demo?

### ISSUE THREAD

**Issue by n8himmel** [mbecker20/komodo#126]
Where do I find the username/password for the demo site?

**Comment by Chloe-ko** [comment]
I don't think they are documented anywhere, but I recently guessed them to be username `demo` and password `demo` which happened to work

**Comment by mbecker20** [comment]
Correct, `demo` : `demo` work. Updated the readme with this info.

**Comment by Synaesthesia0** [comment]
in this moment, demo : demo is not working...

**Comment by mbecker20** [comment]
I fixed it. Unfortunately users can login with `demo` : `demo` and then change the username / password, seems to be what happened here. Komodo doesn't currently have way to stop users from changing the username / password if they are logged in.
