### ISSUE TITLE
Gitlab webhook Issue - no signature in headers

### ISSUE THREAD

**Issue by seraphblade2010** [mbecker20/komodo#132]
I have deployed a stack via komodo and configured the corresponding webhook on my self-hosted gitlab.
When the webhook is triggered, i get the following problem in komodo-core:
`2024-10-17T10:05:28.220794844Z 2024-10-17T10:05:28.220661Z  WARN stack_pull_webhook{id="670e5718fa1e3321e9fb8ddc"}: core::listener::github: failed to run stack pull webook for stack 670e5718fa1e3321e9fb8ddc | no signature in headers`

The webhook seems to be connecting, gitlab reports an accepted connection as well.

**Comment by seraphblade2010** [comment]
After reading a bit it seems komodo expects a different structure of the payload?
Is there any way I can correct it in Gitlab using the "Custom webhook template" Option or is this something that needs to be changed in komodo itself?

I hope its the former and I can finally use komodo and replace portainer with it ^^

**Comment by lucacri** [comment]
Same identical problem here, and same goal (replace portainer)

**Comment by mbecker20** [comment]
I see, the Gitlab api also is different than Github here. The will send your webhook secret in plain text on `X-Gitlab-Token`, rather than generate a signature. It looks like Gitlab do have this feature in the pipeline (opened 7 years ago, 1 month they updated in progress) https://gitlab.com/gitlab-org/gitlab/-/issues/19367#note_2064775564

Anyways I will have to release a patch to account for the way they currently do it.

**Comment by seraphblade2010** [comment]
Nice, thanks for the info ^^
Any Idea if the patch could be out the next couple of weeks or if the coding will be more complex / you have other things in the pipeline before then?

**Comment by mbecker20** [comment]
I just had 1.16.0 in the pipeline. I can release this as patch to 1.16

**Comment by mbecker20** [comment]
[1.16.3](https://github.com/mbecker20/komodo/releases/tag/v1.16.3) adds support for the Gitlab authentication method.

After upgrading Komodo, you can edit your configured webhook urls on Gitlab side, just change `github` to `gitlab` in the webhook URL.
