### ISSUE TITLE
Skip confirmation on actions like start and stop

### ISSUE THREAD

**Issue by Felitendo** [mbecker20/komodo#133]
First of thanks for making this! But there is one thing that is driving me crazy everytime.
It's the fact that I have to type in the name of the stack everytime I want to pause, stop or delete it.
I get that it makes sense to have a confirmation (especially for deleting stacks), but why not make it so we have to press delete twice instead of typing in the name over and over again?

(FYI: I know you can copy the name with one click, but it's still anoying on mobile where the keyboard opens everytime and moves the page around.)

Therefore I would suggest a toggle in the settings where we can turn this off :)

**Comment by LawMixer** [comment]
Enable/disable this value:

https://github.com/mbecker20/komodo/blob/main/test.core.config.toml#L13

**Comment by Felitendo** [comment]
> Enable/disable this value:
> 
> https://github.com/mbecker20/komodo/blob/main/test.core.config.toml#L13

Great! I didn't know this existed :)

**Comment by mbecker20** [comment]
It also is in the default `compose.env`: https://github.com/mbecker20/komodo/blob/main/compose/compose.env#L41
