### ISSUE TITLE
Git stored config files for docker-compose deployments

### ISSUE THREAD

**Issue by seraphblade2010** [mbecker20/komodo#135]
I have some docker-compose stacks that need additional configuration in the form of additional .yaml files (not compose files) that are loaded as volumes. Currently i use the repo-cache folder inside the core volume to grep this information for the deployment but I would like a simpler version of that. Negative side of that is that sometimes the sync is not up-to-date, especially when using webhooks to automatically redeploy the stack when changes are detected.

For example, in portainer there is an option named "relative path volume" where the currently selected git-repo folder where the docker-compose is stored and the corresponding subfolders get copied to the host while deployment and after that one can simply use "./config" for the volume specification in docker-compose. This also guaranties that that the config is always up-to-date because the copy-function is perfomed before the docker-compose up.

(Im the reddit comment 😄 )

**Comment by mbecker20** [comment]
Hi, if I understand correctly, you have `.yaml` files (not compose files) in one or more repos, and you need to mount them / copy contents into containers?

If so, you have a couple of options.

1. Use the Repo resource:
 Create a new Repo pointing to the source git repo, and attach the Core server to clone on. Clone the repo, and setup a webhook to automatically pull the repo when any changes are pushed there. Update the Stacks to point to the location of the cloned repo, something like `/etc/komodo/repos/{name}/config_1.yaml`.

2. If you commit both the .yaml config file and the compose file to the same repo, you can use Stack `git repo` sources mode directly. Previously, the repo was deleted from the host right after the stack was deployed, but now the repo is kept on the host and will use `git pull` to keep it updated before deploy. So you can reference the other files in the repo from you compose files.

**Comment by mbecker20** [comment]
Also note when dealing with Webhooks, the `Procedure` resource is your friend. You can make a Procedure that first can execute `Pull Repo` on a `Repo` resource, then `Deploy Stack` on a `Stack` resource (or use `Deploy Stack If Changed`).

You can also point a webhook to trigger the Procedure. It is a lot more dynamic than webhooks pointing to a specific resource. I did resource specific webhooks first and will continue to support, but since Procedures feature I have realized using Procedure webhooks is better in case you want to add another execution later, you don't need to change any webhooks on your git provider interface.

**Comment by seraphblade2010** [comment]
Thanks for the quick answer ^^
I will test the periphery path today and give feedback if applicable.

For the procedures: I tried to use them exactly how you described but when using 6-7 webhooks komodo gets 6-7 requests each time there is an activity in the repo and will try to pull the repo in the procedure but only one procedure gets done while all others fail because of "resource busy". 

While writing I got the idea: A single procedure should be enough i guess? Just add all stacks into the procedure and set them to "if changed" so only one git pull is done, will also test.

If im alread writing: The repo resource is meant to copy the repo onto the specified host, yes? Which path is it and can I specify it? I tried to specify the path with one of the options it gives but no files where copied to my target, even tough in the logs of the job it specified my path. Any idea?

**Comment by seraphblade2010** [comment]
Quick thing to add: The feature I mean on the git resource is 'Clone Path".
My specified path does not seem to work, whatever Im trying.

Currently im trying '/infrastructure/komodo/git/' (Host-path) and the path is specified in the logs but nothing exists there.
When i leave it empty, it seems to copy inside the mounted volume folder for the periphery, under: /(mounted folder path)/repos/(my git repo). Is that thesis right?

**Comment by mbecker20** [comment]
Hi, did you figure this out? When you use custom clone path, it should be absolute path, and it will clone to this absolute path inside the container. This directory may not be mounted. It makes a bit more sense to use this when using systemd managed periphery, ie when you run periphery outside the container, in which case you can clone to repo to any location on your host that the periphery user has permission to.
