### ISSUE TITLE
[Feature] Export whole config file that defines komodo

### ISSUE THREAD

**Issue by seraphblade2010** [mbecker20/komodo#141]
As someone who wants to switch from the environment variables to a user supplied config file and a way for disaster-recovery when experiencing data loss, I would like to export the whole current komodo config and paste it into the volume mount for the config file.

I know that we can export the currently selected UI Elements as toml export but to switch from ENV to config file and a way for disaster-recovery one needs to export the whole config and supply it to the container at startup, so my idea.

Edit: Why do I want this?
In case of emergency-recovery of data I do not want to reproduce every single config I have made per hand but instead just feed it my existing config file so that when I rebuild my homelab from scratch I can supply komodo with the backup of the config file (stored in git for example) and mount it to the container at startup.

**Comment by mbecker20** [comment]
I am not sure about how this can be used to do emergency recovery. You can do regular backups of your Komodo configuration files, or have them stored in git etc, whether you are using `compose.env` or `core.config.toml` or both of them. Users should set that up now and you will be covered here without any other feature.

In terms of moving from `compose.env` configs to `core.config.toml`. I would recommend users start from the commented config file from https://komo.do/docs/setup/advanced#mount-a-config-file and move their configs over to the commented file, just takes a few moments.

**Comment by seraphblade2010** [comment]
Ah, i have misinterpreted the resource sync feature and based on my wrong take on it this issue was born, sorry for the inconvenience :(

Just a quick question: Can I export my already defined resources via the toml option in the UI and add it to the resource sync pointed git repo without any worries? From there on I would then configure most, if not all resources, from this config file and add / remove new ones.

**Comment by mbecker20** [comment]
No problem. For your question, yes you can, this is the idea:

- Use TOML buttons in UI to export the toml, copy the contents
- Paste them into a `.toml` file in a git repo, and point a new ResourceSync at the git repo.
- It shouldn't have any "Pending" changes. The Resource Sync matches what you have in the UI, after all you just exported.
- Try making a change to the resource file, you can commit the change from your local editor, or you can use the Komodo UI to edit the via the `Info` tab (it can commit to your repo if the token has write privileges).

Feel free to ask any more questions here (or join the [Discord](https://discord.gg/DRqE8Fvg5c))
