### ISSUE TITLE
BUG: stack redeploy fails because of locked repo

### ISSUE THREAD

**Issue by Lukas-Heiligenbrunner** [mbecker20/komodo#152]
Hey, 
simultaneous redeploys fail sometimes with a lock error. I guess this should be handled by komodo and it should await the lock? 
If this is a duplicate or not a komodo error feel free to close the issue again. 

```
fatal: Unable to create '/etc/komodo/stacks/arr/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

**Comment by mbecker20** [comment]
Do I understand correctly, this error will happen for some deploys causing them to abort with failure log, but if you wait a bit and try deploying again it will work?

**Comment by Lukas-Heiligenbrunner** [comment]
Hey, 
I think this error might be my fault. I'm not sure how this happened, but it only happens for this stack. 
A redeploy action was interrupted and didn't finish (maybe by komodo restart or sth) and I think it didn' release the lock of the git repo somehow. 

![image](https://github.com/user-attachments/assets/f9e90cb4-d2da-4273-b429-c10b1a813113)

I'm not sure if this is a fault from your side. Feel free to close the issue. :)
