### ISSUE TITLE
[Feature] Add URL Builder type

### ISSUE THREAD

**Issue by scorp200** [mbecker20/komodo#153]
![image](https://github.com/user-attachments/assets/677d2897-0457-46ca-a1ee-b27018fac081)

Add a periphery URL "Builder Type" to allow adding a device that is running Komodo periphery by URL.
This is to avoid adding it as a server and having Komodo pull all info about it such as containers.

**Comment by mbecker20** [comment]
Done in https://github.com/mbecker20/komodo/releases/tag/v1.16.6
