### ISSUE TITLE
Translate container network to it's respective network

### ISSUE THREAD

**Issue by animecyc** [mbecker20/komodo#154]
Didn't see this reported or suggested anywhere but It would be great it Komodo could translate a container network (i.e. `container:<container-sha>`) to the network that container belongs to. It also seems to report the network as "red" even though the container and its repsective network is healthy.

<img width="453" alt="Screenshot 2024-10-26 at 3 09 42 PM" src="https://github.com/user-attachments/assets/159c8188-ccdd-4798-9359-cc29cb841cde">

**Comment by mbecker20** [comment]
The value you see here comes from the "Name" field of the Docker API [list networks] (https://docs.docker.com/reference/api/engine/version/v1.37/#tag/Network/operation/NetworkList) response.

It seems like a similar issue to https://github.com/mbecker20/komodo/issues/71, in that case Docker uses the network ID as the "Network Name". In this case, it seems to be using a name related to the Container ID.

Could you provide the output of `docker network ls --format json` on this host? This will show exactly what docker is giving to Komodo for network list.

**Comment by animecyc** [comment]
I don't believe this is directly related to #71, though its possible that its in a similar problem space. I was curious to see if container networks could be translated to their respective network name(s). Here is a full reproduction along with network and container inspection results:

---

**Foo/Bar Compose**
```yaml
services:
  foo:
    image: alpine:latest
    command: tail -f /dev/null
    network_mode: service:bar
  bar:
    image: alpine:latest
    command: tail -f /dev/null
    networks:
      bridge: {}
networks:
  bridge: {}
```

**Komodo UI**

<img width="1138" alt="Screenshot 2024-10-27 at 11 45 46 AM" src="https://github.com/user-attachments/assets/7fc561b6-1077-4d18-9939-9c6daebcb87e">

**Foo Container**
```jsonc
/* $ docker container inspect repro-container-network-foo-1 --format json | jq '.[].HostConfig.NetworkMode' */
"container:6e38d7f74f7b4543796aa2aeccfecb9f6ee26d9835c3aeac2645dfbf0d9a7761"
```

**Bar Container**
```jsonc
/* $ docker container inspect repro-container-network-bar-1 --format json | jq '.[].HostConfig.NetworkMode' */
"repro-container-network_bridge"
```

**Bar Network**
```jsonc
/* $ docker network ls --filter name=repro-container-network --format json | jq */
{
  "CreatedAt": "2024-10-27 11:35:05.069762106 -0700 PDT",
  "Driver": "bridge",
  "ID": "fb81aa05b3a8",
  "IPv6": "false",
  "Internal": "false",
  "Labels": "com.docker.compose.version=2.29.7,com.docker.compose.network=bridge,com.docker.compose.project=repro-container-network",
  "Name": "repro-container-network_bridge",
  "Scope": "local"
}
```

**Comment by mbecker20** [comment]
Ok that definitely clarifies what you mean, thanks for the write up. It definitely doesn't handle this edge case, I'll see what I can do.

**Comment by mbecker20** [comment]
Fixed in https://github.com/mbecker20/komodo/releases/tag/v1.16.6
