### ISSUE TITLE
Stack reporting unhealthy when scaled up

### ISSUE THREAD

**Issue by animecyc** [mbecker20/komodo#155]
Not sure if this is a bug or a misconfiguration on my end but when I scale a service up Komodo reports that the stack is unhealthy even though its healthy. Scaling it back down to 1 makes the stack healthy again.

---

<img width="420" alt="Screenshot 2024-10-26 at 3 16 31 PM" src="https://github.com/user-attachments/assets/b0ae95b5-79ef-4b56-9b24-20d0ed175552">

**Comment by seraphblade2010** [comment]
@animecyc  Scaling up probably refers to docker swarm? If yes, the support for docker swarm is not out yet, roadmap says 1.17 will bring that.

**Comment by mbecker20** [comment]
Can you clarify what you mean by scaling up? For example, if you increase the "replicas" in docker compose and "Deploy" Stack, it should work currently to pick up the replicas.

**Comment by animecyc** [comment]
> @animecyc Scaling up probably refers to docker swarm? If yes, the support for docker swarm is not out yet, roadmap says 1.17 will bring that.

Not referring to docker swarm here -- I meant to say scaling up replicas.

> Can you clarify what you mean by scaling up? For example, if you increase the "replicas" in docker compose and "Deploy" Stack, it should work currently to pick up the replicas.

To clarify, yes I meant scaling up replicas, I've got replicas set to 4 in the compose file. It does pick up the replicas but it still reports as unhealthy.

**Comment by mbecker20** [comment]
Fixed in https://github.com/mbecker20/komodo/releases/tag/v1.16.6
