### ISSUE TITLE
Can't figure how to add a second disk to be "monitored" 

### ISSUE THREAD

**Issue by ValgulNecron** [mbecker20/komodo#158]
on periphery in the volumes there is 
- /:/mnt/sys:ro
and this disk does show with the right usage and capa

but if i try adding a second one with something like 
      - /mnt/d:/mnt/d:ro
this second disk is not detected / not shown on the app.

**Comment by mbecker20** [comment]
Can you try removing `PERIPHERY_INCLUDE_DISK_MOUNTS` from your `compose.env`? Once you see the full list, you can add it back with all your paths in comma seperated list.

https://github.com/mbecker20/komodo/blob/main/compose/compose.env#L128

**Comment by ValgulNecron** [comment]
Hi, 
checking back at this var I h've made a typo by writting /mnt/D instead of /mnt/d
thanks for the help
