### ISSUE TITLE
No rounding applied in metrics

### ISSUE THREAD

**Issue by gitcatpeter** [mbecker20/komodo#198]
Cosmetic issue.

Don't know about other metrics, but ServerCPU is providing such an earthshattering accuracy ;-)

```
[WARNING] ServerCpu for <xyz>
Hit 92.11054992675781%
```

**Comment by mbecker20** [comment]
It is stored as an f64, I didn't think the upstream should modify it, the Custom Alerter implementation receiving alert should format the float as they see fit. If you are using @FoxxMD Alerters, you should direct this request to that implementation.

**Comment by FoxxMD** [comment]
This can be closed afaik. Decimal formatting is implemented in ntfy/gotify alerters

**Comment by gitcatpeter** [comment]
Yes, thank you, working well.

**Comment by mbecker20** [comment]
Good to hear!
