### ISSUE TITLE
[Feature] Docker stack support

### ISSUE THREAD

**Issue by ocrumbs** [mbecker20/komodo#201]
This is an awesome project. I love that it is so lightweight. I would like to know if [Docker Stack](https://docs.docker.com/reference/cli/docker/stack/) is something on the roadmap.

While compose is great, docker stack is more production ready friendly and has built-in support for secrets, blue green deployment and more. It would be a great fit for komodo IMHO.

Thanks

**Comment by mbecker20** [comment]
Yes I think docker swarm support would be really awesome, and have had an issue for this for quite a while here #37. I'm still consolidating and clarifying the current features before moving onto support for this.
