### ISSUE TITLE
[Help] How to provide path to "Run Directory" in UI mode?

### ISSUE THREAD

**Issue by ocrumbs** [mbecker20/komodo#202]
Trying to add a stack using the UI mode. However, not sure how to provide  path to "Run Directory".

![image](https://github.com/user-attachments/assets/536651d4-1878-4177-8a29-aa0dfa10adbf)

**Comment by mbecker20** [comment]
Usually when you create a Stack, you will select "Files on Server" mode.

Its not very intuitive as I didn't plan for switching modes after creation, but if you go to the Compose File editor and Ctrl + A, backspace (delete the contents) the UI will let you select the Stack deploy mode again.

**Comment by mbecker20** [comment]
The more Komodo way is to add the Stack to a ResourceSync, update the Toml contents with `files_on_host = true`, and sync the changes in.

**Comment by ocrumbs** [comment]
Thanks a lot. Yes, I really like that fact the resources in Komodo can be bundled as toml config, makes it really powerful in so many ways. I am certainly going to use it.

However, one of my usecases here was to quickly bundle up a compose file which is already there on path but edit them in the UI and vice versa. Right now if I choose **File on Server** mode, it is not possible to edit it in the UI (or may be I missed it)

What I think would be more productive is to provide a volume mount path (**Run Directory**) in **UI Mode** option. Komodo pulls in the compose file from the mount path as usual but now is editable via the UI.

Or the other way around would be to provide UI in the **File on Server** mode, which ever is easier :smiley:

**Comment by mbecker20** [comment]
If you navigate to the Stack page for a Files on Server Stack, you can edit the contents from the Info tab. It even works for Git Repo based compose file, you can edit it from within the same Info tab if you supply a git token with write permissions.

Same pattern for Resource Sync with the toml files. They can be Files on Server or Git repo based, and also be edited from Info tab.

**Comment by ocrumbs** [comment]
Ah, I had to first save it to see it. Nice :pray:
