### ISSUE TITLE
Availability to Configure Komodo Health Check Connection Timeout to Servers

### ISSUE THREAD

**Issue by carl-ac** [mbecker20/komodo#205]
Hi,

We’ve encountered an issue where some of our team’s servers are consistently entering a "not ok" status in Komodo. 
However, upon investigation, the servers themselves appear to be functioning normally, and there are no indications of network issues (e.g., firewall rules blocking traffic).

Observations:
After further debugging, we suspect the issue might be related to network latency between the Komodo server and the target server. Specifically, the network latency appears to exceed Komodo's default connection timeout for health checks.

Here are some latency measurements we observed:
```
64 bytes from 10.*.*.* (10.*.*.*): icmp_seq=1 ttl=61 time=255 ms  
64 bytes from 10.*.*.* (10.*.*.*): icmp_seq=2 ttl=61 time=254 ms  
64 bytes from 10.*.*.* (10.*.*.*): icmp_seq=3 ttl=61 time=255 ms 
```
Additionally, we found that the request time from the Komodo server to the target server can occasionally exceed 1 second.

Feature Request:
It would be highly beneficial to have the ability to configure the health check connection timeout for servers in Komodo. This feature would allow us to adjust the timeout to accommodate servers with higher network latency.

**Comment by carl-ac** [comment]
Yes it's good idea and thanks for the feedback!

**Comment by gitcatpeter** [comment]
+1
I was just to report the same. I'm getting random "Server Unreachable" which are immediately followed by cancellations.
This only happens to last two servers (out of 6) I added to Komodo  - if being the last has any meaning for polling....

Very lightly loaded servers in the same subnet as Komodo-core, even same hypervisor.
No issues observed in logs.

**Comment by gitcatpeter** [comment]
Just to give you some idea, Zabbix uses 3s by default, configurable in the range of 1-30s
https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_server#timeout

**Comment by gitcatpeter** [comment]
3s timeout solved the problem for me.

**Comment by carl-ac** [comment]
Thanks so much for handling this!
