### ISSUE TITLE
[bug] File on server doesn't find docker-compose.yml file

### ISSUE THREAD

**Issue by tm-brg** [mbecker20/komodo#215]
I use 1.16.12,  I have a compose file but I can't redeploy it because komodo doesn't find the file on the server but the path is good.

![image](https://github.com/user-attachments/assets/7b912d11-65f2-455b-aaf1-5732457a8737)

**Comment by mbecker20** [comment]
If you are running Periphery in docker container, the path is seen from inside container. You have to mount the file into the container.

Note that the mount should be the same on both side, like `- /home/ubuntu/docker:/home/ubuntu/docker`. This ensures that relative file mounts will work correctly, re this discussion: https://github.com/mbecker20/komodo/discussions/180

**Comment by froststevefrost** [comment]
> If you are running Periphery in docker container, the path is seen from inside container. You have to mount the file into the container.
> 
> Note that the mount should be the same on both side, like `- /home/ubuntu/docker:/home/ubuntu/docker`. This ensures that relative file mounts will work correctly, re this discussion: #180

This worked for me, thank you!
