### ISSUE TITLE
[Feature] Additional Alert Provider Support

### ISSUE THREAD

**Issue by hobybrenner** [mbecker20/komodo#226]
Is there any chance at adding support Apprise for alerting? This would open up alerting for many services.

Apprise allows you to send a notification to almost all of the most popular notification services available to us today such as: Telegram, Discord, Slack, Amazon SNS, Gotify, etc.

https://github.com/caronc/apprise

Thanks!

**Comment by FoxxMD** [comment]
I've got a [laundry list of Alerters implemented for Komodo](https://github.com/FoxxMD/komodo-utilities) and apprise was next on my list. I can get this implemented maybe this week or soon thereafter.

**Comment by FoxxMD** [comment]
@hobybrenner you can try out the alerter at [`foxxmd/deploy-apprise-alerter`](https://github.com/FoxxMD/deploy-apprise-alerter)

If you have issues:

* with the Resource TOML or stack/ENV configuration _specifically_ pleas make an issue on [`foxxmd/deploy-apprise-alerter`](https://github.com/FoxxMD/deploy-apprise-alerter)
* with the functionality of the alerter itself (bugs, not working, env not parsing correctly, etc...) please open an issue on [`foxxmd/komodo-utilities`](https://github.com/FoxxMD/komodo-utilities)

**Comment by mbecker20** [comment]
Thanks @FoxxMD!
