### ISSUE TITLE
feature: Add Discord webhooks to Alerters 

### ISSUE THREAD

**Issue by LawMixer** [mbecker20/komodo#23]
I do not use Slack unfortunately, but I do use Discord daily - would love to make this a thing!

**Comment by mbecker20** [comment]
Agreed, slack is good for businesses but not individuals, I have this in my todo. There is also structure to add this and many more inbuilt endpoints.

Additionally, if you know Rust, you can use the starter codebase I made for building Custom Alerters. [https://github.com/mbecker20/monitor/tree/main/bin/alerter](https://github.com/mbecker20/monitor/tree/main/bin/alerter).
Once you have the Alert in code you can do whatever you want with it.

**Comment by mbecker20** [comment]
You can also use Vector ([https://vector.dev/](https://vector.dev/)) as Custom Alerter endpoint

See [https://vector.dev/docs/reference/configuration/sources/http_server/](https://vector.dev/docs/reference/configuration/sources/http_server/)

Then you can route alerts to any of the Vector Sinks here: [https://vector.dev/docs/reference/configuration/sinks/](https://vector.dev/docs/reference/configuration/sinks/)

You can consider a logging stack like Grafana / Loki / Tempo, or VictoriaLogs stack, to send all logs / alerts to. Then route everything to your messaging like Discord from there. This is more scalable setup and kind of fun to set up if you are into this. You can set it all up with Monitor too

**Comment by TomKauffeld** [comment]
While Discord is not implemented, you can already send notifications to a Channel using [Discord Slack-Compatible Webhook](https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook):
- Create a webhook in Discord on the channel you want the message
- Create a new Alerter on Komodo with as Endpoint type Slack
- Paste the webhook url as the endpoint with `/slack` at the end
