### ISSUE TITLE
Question: Committing mounted files

### ISSUE THREAD

**Issue by Hugo-Persson** [mbecker20/komodo#230]
Hi!

I have the scenario where I have a mounted volume to one of my containers, the container then writes data to a file. I wish to sync this file with git with periodical commits. Do Komodo have some way to achieve this?

Otherwise, I can create a cron job that runs git add, git commit and git push periodically.

**Comment by mbecker20** [comment]
I'm not sure there's anything specific to this feature. Maybe something with #47 (scheduling, not implemented). I'd just use the Cron job for now.
