### ISSUE TITLE
local login

### ISSUE THREAD

**Issue by adamphetamine** [mbecker20/komodo#235]
I fully admit this is a dumb issue, but I could not find how to solve-

**After deployment, could not figure out how to login using local credentials**

I seem to recall seeing something to indicate that the first logged in user is made Admin, but I couldn't find that text again, and this didn't work for me- ie. couldn't login with any combination of user/pass

This is using latest version on Ubuntu 22.04, with the MongoDB setup.

**Comment by mbecker20** [comment]
Hi, to make your admin user, enter you username and password, and hit the "Sign Up" button (not Login).
