### ISSUE TITLE
Add simple email/smtp alerter

### ISSUE THREAD

**Issue by dupondje** [mbecker20/komodo#239]
Hi,

First of all thanks for the nice piece of software :)
The Auto-update feature is something that I would like to use more. BUT...

Would it be possible to implement some simple notifications via email in the Alerter?
I would just like to receive some simple email when there is an update available or if some update was executed.

**Comment by mbecker20** [comment]
Hey, you can use the Apprise Alerter from @FoxxMD:

https://github.com/FoxxMD/deploy-apprise-alerter

**Comment by FoxxMD** [comment]
Specifically, apprise can do emails https://github.com/caronc/apprise?tab=readme-ov-file#email-notifications
