### ISSUE TITLE
Feature Request: Add ability to use self hosted Oauth provider

### ISSUE THREAD

**Issue by arcoast** [mbecker20/komodo#29]
With monitor being very much a self hosted application, it would be great if we could setup OAuth with providers other than GitHub & Google, rather instead use self-hosted providers such as Authelia (which I currently use with several applications, and am happy to test) or Authentik.

**Comment by mbecker20** [comment]
Totally agree. Ill add the todo tag

**Comment by Node815** [comment]
I very much look forward to the ability to manage this.

**Comment by mbecker20** [comment]
v1.15+ adds support for self host OIDC provider

**Comment by arcoast** [comment]
> v1.15+ adds support for self host OIDC provider

Thank you, Will try and test this out as soon as I can.  Much appreciated!
