### ISSUE TITLE
Volume, Image  & Network Management?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [mbecker20/komodo#33]
Hi, are there any plans to support volume, image and network management?

**Comment by mbecker20** [comment]
Yes absolutely. Docker networks specifically are noted on the [roadmap](https://github.com/mbecker20/monitor/blob/main/roadmap.md). 

Volumes and images should also be included here, I will expand the roadmap to support these in 1.14, as they should be a bit easier to manage.
