### ISSUE TITLE
Improve In-editor UI of compose files

### ISSUE THREAD

**Issue by DanCardin** [mbecker20/komodo#39]
Hi, we interacted on reddit, resulting in (i think) the "Files on Server" toggle option. Very much liking Monitor so far!

Would it be possible to allow editing said file akin to the "Compose File" text box that's available when "Files on Server" is not toggled?

This would basically get it onto-par with portainer/dockge, in that i could author an entire compose file from the web app, while also having the data just be plain text files. (lmk if this actually already possible, and i'm just being dense!)

I'd also request more "code editor"y experience (syntax highlighting, ctrl+/ comments, <tab> as tab; but that's definitely a completely separate Issue, as well as presumably a much larger investment/involvement of some js component.

**Comment by mbecker20** [comment]
Hi, first of all, thanks for you interest in the project and the helpful feedback!

Correct, it is not possible to edit the files from the UI when using "Files on Server" mode. And I don't think Monitor's lack of code-editor features when it comes to compose files is a separate issue at all -- If the editor is as bad as it is, users won't want to use the feature. So I think it makes sense to prioritize "editing Files on Server" features _after_ improving the editor UI.

And then it comes down to priorities for me. Users using either "Git Repo" mode or "Files on Server" mode can already edit the file using their favorite editor (check out VSCode over SSH!) and have a good experience here. Many will prefer using their own editor over Monitor editor even if it did have a good UI, especially power users. So I didn't feel it was a great use of time at this point.

With that said, I do want to support this convenience feature, and did look a bit into figuring out web editor frontends, syntax highlighting, context-aware tab indentation. It really just needs some time dedicated to this part. I also think it would be a really good task for the community to handle, as some others have much more experience with this than either me or @karamvirsingh98 .

Once the UI is sorted, I will revisit this feature to edit compose files on the host in "Files on Server".

**Comment by mbecker20** [comment]
Going to try implementing [https://www.npmjs.com/package/@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react)

**Comment by FoxxMD** [comment]
There's also [`monaco-yaml`](https://github.com/remcohaszing/monaco-yaml) which is a drop-in replacement for the official `monaco-editor` and adds built in support for yaml plus validating against a JSONschema ([`compose.json` schema](https://github.com/compose-spec/compose-spec/blob/main/schema/compose-spec.json)) [like this](https://github.com/mbecker20/komodo/compare/main...FoxxMD:komodo:monacoComposeEditor#diff-839543ee0bf0e69f979e7647e66cf33c1c5be6df9b4860f19dfe7738d603a036R9)

**Comment by mbecker20** [comment]
v1.15+ implements monaco editor to improve this
