### ISSUE TITLE
Is this something I can do with this project

### ISSUE THREAD

**Issue by apperrault** [mbecker20/komodo#41]
Hi there, this really isn't an issue, more of a question that I can't find an answer to.  A while ago, I started using a project Dokemon (https://github.com/productiveops/dokemon) that allows me to setup a master system, add a bunch of agent systems, and then I can create and store my docker-compose.yml files in Github, point the library in this project to those individual files and basically deploy them with a few clicks.

Is that something that this project can, or plans to be able to do?  I like this other project, but shortly after starting the project, the owner ran into some issues personally, and abandoned it, and I have been looking for something to replace that functionality, this looks like it might be heading down that road.

thanks

app

**Comment by mbecker20** [comment]
Hi app!

Monitor is absolutely able to do this using the `Stack` resource: [https://docs.monitor.dev/docs/resources#stack](https://docs.monitor.dev/docs/resources#stack). 

You can see Stacks in action in the demo: [https://demo.monitor.dev/stacks/66b7d69f7668f9f0d1cefd2d](https://demo.monitor.dev/stacks/66b7d69f7668f9f0d1cefd2d). You can "Signup" with any username or password (note the default behavior does not allow any user to sign up, this is just for demo).

The overall structure of Monitor is the same, the "master system" is called Monitor Core, and you can connect as many servers as you want using the Periphery agent: [https://docs.monitor.dev/docs/intro#architecture-and-components](https://docs.monitor.dev/docs/intro#architecture-and-components).

Looking at `dokemon`, it looks very similar to Monitor and I believe Monitor will be a mostly drop in replacement.

One area of difference is `dokemon` Environments / Variables, just noticing from a brief look over there.

Monitor supports passing Environment Variables to your compose Stacks, and can interpolate Variables into the environment it passes to the stack.

<img width="1181" alt="Screenshot 2024-08-21 at 9 33 39 PM" src="https://github.com/user-attachments/assets/0f9fabf5-76f7-4dff-826b-c16b80211807">

In terms of `dokemon` Environment feature, it looks like something to change the value of certain Variables:
<img width="806" alt="Screenshot 2024-08-21 at 9 21 49 PM" src="https://github.com/user-attachments/assets/94590999-f688-4bf7-b13a-c7f53e45578f">

Monitor does not support this though, it just provides a flat list of Variables. You would need to migrate your Variables to have names like VARIABLE_1_STAGING and VARIABLE_1_PROD using Monitor:

<img width="1202" alt="Screenshot 2024-08-21 at 9 22 56 PM" src="https://github.com/user-attachments/assets/ee313ae9-3dd4-40de-9f2f-e3248a7fa03a">

Overall `dokemon` is a cool project and in fact very similar to Monitor. I believe Monitor has more features and is certainly NOT dead, with a clear roadmap for future support: [https://github.com/mbecker20/monitor/blob/main/roadmap.md](https://github.com/mbecker20/monitor/blob/main/roadmap.md).
