### ISSUE TITLE
Substitute variable in Extra Commands

### ISSUE THREAD

**Issue by beraj** [mbecker20/komodo#42]
This may be more of a question or something I am doing wrong, but wanted to mention it in case it is something that needs attention.  I am working on moving all my containers over to deployments in Monitor.  One of my containers needs extra commands appended:

--workspace=/siyuan/workspace/ --accessAuthCode=${AuthCode}

It appears that the environment file variable doesn't get substituted.  If I replace the variable with a literal, it is working fine.  If this is something I am doing incorrectly, I apologize.  I tried several different iterations including the syntax noted in docs of '[[AuthCode]]'.

Thanks for your work on this project!  It is really cool and I am having fun playing with it.

**Comment by mbecker20** [comment]
Good point, the variables are currently only interpolated into environment. 

I've considered this as well and will add this in 1.14
