### ISSUE TITLE
Ability to restart all containers and start them back up

### ISSUE THREAD

**Issue by LawMixer** [mbecker20/komodo#43]
> in case something that needs to be brought to all of the containers, so we do not have to restart all of them.

Originally featured in the discord server: https://discord.com/channels/1272479750065094760/1276214023192318045

**Comment by mbecker20** [comment]
Sure, the API currently includes StopAllContainers, which will stop all containers on target server: [https://docs.rs/monitor_client/latest/monitor_client/api/execute/struct.StopAllContainers.html](https://docs.rs/monitor_client/latest/monitor_client/api/execute/struct.StopAllContainers.html)

Similar API can be added for `RestartAllContainers`, and additionally will complete the full control api (same as single container level) with `StartAllContainers`, `PauseAllContainers`, `UnpauseAllContainers`, `DestroyAllContainers`

This as an execution targeting a `Server`, it is limited to RestartAllContainers on a server alone. The feature expansion for `Procedures` in discussion with @C0untZero will also help, you can make a procedure triggering `RestartContainer` that matches against all your Deployments using *
