### ISSUE TITLE
[Feature] Global webhooks

### ISSUE THREAD

**Issue by Lukas-Heiligenbrunner** [mbecker20/komodo#48]
As discussed on dc:

Since adding all stack webhooks each by each to devops pipelines can be tedious ->
Provide a global webhook for auto-redeploy and refresh actions. 
Similar to individual webhooks for stacks create a webhook which triggers stack redeploys which have changed since last webhook call (or git commit).

Webhook might be filterable with GET parameters:
 * type=stack
 * server=servername
 * git_repo=reponame
 * stack_name=mystack.yaml

This redeploys only the stacks which remain after filtering.
🦎

**Comment by mbecker20** [comment]
Thanks for the write up.

I was thinking about this some more, and wonder whether this is better accomplished using the upcoming feature expansion to Procedures: [https://github.com/mbecker20/monitor/issues/48](https://github.com/mbecker20/monitor/issues/48)

You can configure procedures to do actions based on filters and it should be more capable (can do multi - stage actions composed of different action types)

And then you just add the git webhook to trigger the procedure (already can trigger procedure from webhook)

Will come back and see whether this is needed following the Procedure improvements.

**Comment by Lukas-Heiligenbrunner** [comment]
Great! Thanks for your work.  
I guess this issue can be closed then. The other features mentioned may be added in the future, but are by no means a priority.
