### ISSUE TITLE
[Feature] secret (variable) UI configuration

### ISSUE THREAD

**Issue by C0untZero** [mbecker20/komodo#51]
At the moment, secrets are only configurable through the core config file.
It would be nice if we could also do this through the UI.

A simple checkbox next to a variable marking it as secret or not would do the trick!

**Comment by mbecker20** [comment]
Good Idea. Will add this feature "mark Variable as secret", which will cause it to be hidden in UI / Logs, just as the Secrets defined in config file are.

**Comment by C0untZero** [comment]
Maybe the Value field in the UI should be obfuscated with asterisks when variable is marked as secret?

**Comment by mbecker20** [comment]
Added this obfuscation in this commit: [https://github.com/mbecker20/komodo/commit/a0021d1785606ba7fc9136b8821c4e6bf18c13f7](https://github.com/mbecker20/komodo/commit/a0021d1785606ba7fc9136b8821c4e6bf18c13f7)

Will be included in 1.14.0 stable.
