### ISSUE TITLE
MongoDB relies on AVX enabled CPU. If you can't run Mongo, use Postgres or Sqlite backends.

### ISSUE THREAD

**Issue by mbecker20** [mbecker20/komodo#59]
Users lacking AVX enabled CPUs will not be able to successfully run MongoDB on their host. These users can use the [Postgres](https://komo.do/docs/setup/postgres) or [Sqlite](https://komo.do/docs/setup/sqlite) storage backends, which utilize the awesome [FerretDB](https://www.ferretdb.com/).

**Comment by RKLBusinessDevelopment** [comment]
A workaround that works for me is using an older MongoDB image that doesn't require AVX support. I am using MongoDB 4.4, which I believe to be the last version not requiring AVX support.

**Comment by ajg1111** [comment]
> A workaround that works for me is using an older MongoDB image that doesn't require AVX support. I am using MongoDB 4.4, which I believe to be the last version not requiring AVX support.

There is also a community produced 5.0 MongoDB docker image without AVX.  I've used it in a few projects so far and it's been stable.     docker.io/l33tlamer/mongodb-without-avx:5.0.20

**Comment by retiarylime** [comment]
> There is also a community produced 5.0 MongoDB docker image without AVX. I've used it in a few projects so far and it's been stable. docker.io/l33tlamer/mongodb-without-avx:5.0.20

Tried this and it works. Thank you.

**Comment by helmut72** [comment]
But there isn't an image for Raspberry Pi / arm64. Would be nice if other DBs were supported.

**Comment by mbecker20** [comment]
The Mongo image supports arm64, it is multi platform for some time now.

**Comment by helmut72** [comment]
With Mongo from default compose example:

```
WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!
```

And the Mongo image mentioned in this issue is this one right?

https://hub.docker.com/r/l33tlamer/mongodb-without-avx/tags

This isn't updated since 10 months and is amd64 only:

```
no matching manifest for linux/arm64/v8 in the manifest list entries
```

It would be great if Raspberry is supported as easy as Portainer just works on it.

**Comment by mbecker20** [comment]
I found this tool to support other databases underneath the MongoDB api. [ferretdb](https://www.ferretdb.com).

I'm hoping it will allow user to select between Mongo, Postgres, and SQLite, while Komodo code doesn't need to worry about making any adapter. I'd like Komodo to be able to focus on driving forward the new features and not be bogged down with database adapter and bugs that come with it.

I'll see how this ferretdb works and report back.

**Comment by mbecker20** [comment]
Postgres and Sqlite are supported from 1.14.2, see https://komo.do/docs/setup

**Comment by FoxxMD** [comment]
PSA The Raspberry Pi 5 uses a [Cortex-A76](https://en.wikipedia.org/wiki/ARM_Cortex-A76) that supports the ARMv8.2-A instruction set and can run mongo fine. I've got Core+Mongo running on mine now.
