### ISSUE TITLE
[Feature] Add an option to disable signups

### ISSUE THREAD

**Issue by scorp200** [mbecker20/komodo#60]
currently the only available option is
`KOMODO_ENABLE_NEW_USERS` that disables new users by default

I would like to have an option to completely disable new user signups, no signup button and any api signup calls rejected
and call it something like `KMODO_ALLOW_SIGNUP`

**Comment by mbecker20** [comment]
Supported in 1.14.2 with environment variable `KOMODO_DISABLE_USER_REGISTRATION`
