### ISSUE TITLE
Comments are deleted in Stacks Environments

### ISSUE THREAD

**Issue by FibreTTP** [mbecker20/komodo#63]
When saving a Stacks Environment configuration, any lines beginning with `#` are deleted. Empty lines are additionally deleted:

```
# Test comment

test=variable
```
to just
```
test=variable
```

As far as I know, lines beginning with `#` are ignored by Docker, so there's no reason to be deleting them. This doesn't happen in the Compose file section.

**Comment by mbecker20** [comment]
This is not the reason, Env variables are internally not stored in file form but rather converted to array form: `Array<{ variable: string, value: string }>`.

This form allows for better diffing when using resource syncs. Ie the diff can show just one variables value has changed.

The `config.environment` defined in resource syncs do support full line comments using either # or //

**Comment by FibreTTP** [comment]
It's a bit misleading given that there's an option for the filename directly below.

Not everyone has the need to use Resource Syncs. I suggest changing this to store the field as entered, and ***IF*** a Sync updates the variables, parse for the variables and remove the comments at *that* time. This wouldn't affect functionality for anyone, you can still perform the diff.

**Comment by mbecker20** [comment]
I considered this, however the code complexity would be high. Of course like most feedback I do see the value here and would like to deliver. But it has to be clean and not increase complexity too much or risk more bugs.

**Comment by mbecker20** [comment]
I figured this out, next release will keep your Env file with comments intact

**Comment by mbecker20** [comment]
It saves the comments you make in the Environment section in the ui.  At deploy time they are parsed and written to host, this is so multiple formats can be supported like using : instead of = . Maybe there could be an option to write it as is instead.

**Comment by Twilek-de** [comment]
I think that would be nice. As there is often important information in the comments. If Komodo fails for some reason or someone does not want to use Komodo anymore, all this extra information would be lost for all stacks or would have to be painstakingly recovered.
