### ISSUE TITLE
Do we have a roadmap or release plan?

### ISSUE THREAD

**Issue by Kikkon** [mbecker20/komodo#7]
We accidentally discovered this project, and it has many similarities with one of our current container management services online. We are looking for a project to replace it. However, our functionality is more complex and may involve file distribution, updates, and modifications of container environment variables. Are these features planned to be supported or are they already available? 

If there is an appropriate roadmap, I would be happy to participate in sharing it. 😇

**Comment by mbecker20** [comment]
Hi, thank you for your interest in Monitor. I do have an idea of the next couple of releases following some other feedback I have recieved. I just opened a new file to track the roadmap here: [roadmap](https://github.com/mbecker20/monitor/blob/main/roadmap.md).

In terms of other feature requests, I am happy to work with the community on these. I believe the ones you brought up are already supported:

- File distribution and updates: 
Monitor currently supports the "Repo" resource. You can put files in git, create Repo on all the servers that need the files, and setup a webhook to pull the Repos on git push. (only supports Github provider for now -- see roadmap). For files too large for git, I would reach for a purpose built tool for file syncing, like [https://syncthing.net/](https://syncthing.net/).

- Modifying container environment variables: Monitor supports managing container environment variables, along with lots of other configuration. See [https://docs.rs/monitor_client/latest/monitor_client/entities/deployment/struct.DeploymentConfig.html](https://docs.rs/monitor_client/latest/monitor_client/entities/deployment/struct.DeploymentConfig.html)

If I misunderstood your projects needs, or you have another idea, feel free open an issue starting with the `[Request]` tag :)

**Comment by LawMixer** [comment]
Do you plan on having a good discussion place like GitHub discussions or Discord server in mind for the future or now?

**Comment by mbecker20** [comment]
Yeah I like discord. I'll set that up for the upcoming docker compose release

**Comment by mbecker20** [comment]
Hey, I've set up the discord. I'll make another Reddit post later this week but you guys can join up: [https://discord.gg/DRqE8Fvg5c](https://discord.gg/DRqE8Fvg5c).

I also put it in the readme.
