### ISSUE TITLE
Some containers show network GUID instead of name

### ISSUE THREAD

**Issue by beraj** [mbecker20/komodo#71]
Recently updated to latest version of Komodo. Great stuff!

Just noticed what appears to be a small bug.  Not all containers show the network name under the server info:

![image](https://github.com/user-attachments/assets/4b3ace07-c3fc-4e18-ac86-a7dc9af8cbb9)

**Comment by mbecker20** [comment]
Thanks for the report.

How were the containers created? Stack or Deployment?

**Comment by beraj** [comment]
Hi it seems both.

**Comment by mbecker20** [comment]
Can you provide a compose file / `docker run` command similar to what you use that can reproduce this issue?

**Comment by beraj** [comment]
Sure thing.  In the screenshot above as an example, the sonarr & radarr containers are part of a compose stack (compose file in gitea) and the socket proxy is a single deployment.  Here is snippet from the compose file and the deployment toml:

Compose:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks:
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /localmedia/radarr/config:/config
      - /media/Multimedia/Movies:/movies #optional
      - /localmedia/nzbget/downloads:/downloads #optional
    ports:
      - 65002:65002
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /localmedia/sonarr/config:/config
      - /media/Multimedia/TV:/tv
      - /localmedia/nzbget/downloads:/downloads
    ports:
      - 65003:65003
    restart: unless-stopped

Deployment TOML:
[[deployment]]
name = "u200-socket-proxy"
tags = ["updates"]
config.server_id = "ubuntu-200"
config.image.type = "Image"
config.image.params.image = "ghcr.io/tecnativa/docker-socket-proxy:latest"
config.network = "backend"
config.restart = "unless-stopped"
config.ports = "2375=2375"
config.volumes = "/var/run/docker.sock=/var/run/docker.sock:ro"
config.environment = """
CONTAINERS=1 # Allow access to viewing containers
ALLOW_START=1
ALLOW_STOP=1
IMAGES=1
POST=0 # Disallow any POST operations (effectively read-only)"""

**Comment by mbecker20** [comment]
#I am wondering about the "backend" network config. It's not declared in compose file, was it created with cli? Can you show output of 'docker network ls' and 'docker network inspect backend'

**Comment by beraj** [comment]
Sorry, was out on vacation for a bit.  Here is output of above:

Docker version 27.1.1, build 6312585

NETWORK ID     NAME       DRIVER    SCOPE
9987ae065733   backend    bridge    local
dfb575a5dd8a   bridge     bridge    local
5e9c9c7c619b   frontend   bridge    local
8e386f432d87   host       host      local
5f318ecb72fd   none       null      local

[
    {
        "Name": "backend",
        "Id": "9987ae065733eb5869cc9d95240e34acb75614a8ce1c50f52eda0a4c74d04166",
        "Created": "2024-07-27T03:41:41.65307514Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "0124077d90b3882998b245ad3f50215a29cfb35345e724b8ac60d7d9abd230f5": {
                "Name": "nzbget",
                "EndpointID": "f8e82d16e42299eec02168926d116c49781c0220a6c31e2bdd7460c98f22e2fd",
                "MacAddress": "02:42:ac:12:00:12",
                "IPv4Address": "172.18.0.18/16",
                "IPv6Address": ""
            },
            "0ba1f78c9d17e17aefbfbc719fe9beec1023164df76898ddf3b45b72eedb56fe": {
                "Name": "u200-socket-proxy",
                "EndpointID": "931dc4efee6db8c3675cd8979be063e1e95bbdd225e12193d36e57817524e908",
                "MacAddress": "02:42:ac:12:00:10",
                "IPv4Address": "172.18.0.16/16",
                "IPv6Address": ""
            },
            "15b4b5ffa004c6944cacbeabd316a722a951747352a90b0d354af0264ffa9208": {
                "Name": "paperless-pgbackups-1",
                "EndpointID": "21c4b711107d75e0b3a12ab77f9d9cf18e2deabceae3c85a1ef8d500cfc515cd",
                "MacAddress": "02:42:ac:12:00:0c",
                "IPv4Address": "172.18.0.12/16",
                "IPv6Address": ""
            },
            "1b23b69f005b3198735c5633cdeebd74295584b388c4ac5a2915d73f09a94f5d": {
                "Name": "paperless-broker-1",
                "EndpointID": "ade8989795c5f20d277c17cf407151e390489d3ee4721e0b444815443fb7cc3a",
                "MacAddress": "02:42:ac:12:00:0b",
                "IPv4Address": "172.18.0.11/16",
                "IPv6Address": ""
            },
            "2c79a8942a53c818962794697eeba38f04cdddddb69d396425da0bfada3be699": {
                "Name": "paperless-db-1",
                "EndpointID": "195f9e0e4dc317e9f254d0686a1cc062d5425fe40152c615045c14d748eb778b",
                "MacAddress": "02:42:ac:12:00:08",
                "IPv4Address": "172.18.0.8/16",
                "IPv6Address": ""
            },
            "306cf9fd1575030e14e492c372806b50fa9c8aa12b306091c1dabbb8c9c3e429": {
                "Name": "sonarr",
                "EndpointID": "3dd383f654d79bc144f81975d4adf28195a687e943332e72fea1499782926a10",
                "MacAddress": "02:42:ac:12:00:14",
                "IPv4Address": "172.18.0.20/16",
                "IPv6Address": ""
            },
            "58be5950aec5e2322215e5fcc43e91ea555561ff9c9bc959d235e583270a20ef": {
                "Name": "dashy",
                "EndpointID": "107781e6ec213d6e0d0cf9ce5df5b85585eb928b218c606d741bf76261285c99",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "7883fbfeb7ef1da1ff95e941e954c9f7296aee91ba5ea09023ef767ddd1a9b79": {
                "Name": "radarr",
                "EndpointID": "fd57201a718d9fc69b6a6438e9c9c459ff0e01f6fa4e6b4888e77a01ddfbe998",
                "MacAddress": "02:42:ac:12:00:13",
                "IPv4Address": "172.18.0.19/16",
                "IPv6Address": ""
            },
            "8318c9c5b43bcfa5a3a8751a49b0c70d0019b973a469d9ce85ded296ef4c6e20": {
                "Name": "portainer",
                "EndpointID": "51281ece71ab7a853fd7c7a0caa734120a4c8b1b7897c21f7e9fc0679158fd98",
                "MacAddress": "02:42:ac:12:00:0a",
                "IPv4Address": "172.18.0.10/16",
                "IPv6Address": ""
            },
            "83dae8fcc22cda1c096679c590367e4145f1fce5bc92171443c61e8b0270307e": {
                "Name": "immich_redis",
                "EndpointID": "168ffcfd25d0302cbcea834bd874cbe31c60487aa83620e64b0a43e4d7c617bd",
                "MacAddress": "02:42:ac:12:00:09",
                "IPv4Address": "172.18.0.9/16",
                "IPv6Address": ""
            },
            "8be7a3e813933c3d9a0384c8279609da211508d86360d5a7bb17bd0874df34cd": {
                "Name": "immich_postgres",
                "EndpointID": "da718748c95d8a61a2c333f2c065899736a1368e883e2260140b20a9cb2e15cb",
                "MacAddress": "02:42:ac:12:00:07",
                "IPv4Address": "172.18.0.7/16",
                "IPv6Address": ""
            },
            "9530907b5105aeb7a9f8e2aaf829c640aff6a1e1532227aa160846093ce4b9fa": {
                "Name": "immich_machine_learning",
                "EndpointID": "aa607172345c49495f4fbe59364ba6b1ed991d7e9793ed812d86a6e333f97304",
                "MacAddress": "02:42:ac:12:00:06",
                "IPv4Address": "172.18.0.6/16",
                "IPv6Address": ""
            },
            "9d6c3bc0f3518e2cd82c7bb6703c6e4b3550e5d57dce6c9f8918a6e11aaa78ec": {
                "Name": "immich-pgbackups-1",
                "EndpointID": "e66f15d7406a06082a22b90f6d8f2f1006a13b48276939f761803cf356ad862a",
                "MacAddress": "02:42:ac:12:00:0d",
                "IPv4Address": "172.18.0.13/16",
                "IPv6Address": ""
            },
            "b1788b0c838e7f32b42f6cfeec962b73bacbb8e008fec150c976c60565b0eb9c": {
                "Name": "paperless-webserver-1",
                "EndpointID": "75b8d644f3756c7b40241f8ef943f9210d5364d05f0305bd37f1e2ef4ebe7768",
                "MacAddress": "02:42:ac:12:00:11",
                "IPv4Address": "172.18.0.17/16",
                "IPv6Address": ""
            },
            "bd9955ab1bf9d1f40899809bf0bcb5126f946fc61599dae1ecec5313e5ad3bcc": {
                "Name": "paperless-tika-1",
                "EndpointID": "25b5c497c0032ef2cd2a86b29a0ceea5467b564ef76368226556ba9b152c9ca2",
                "MacAddress": "02:42:ac:12:00:05",
                "IPv4Address": "172.18.0.5/16",
                "IPv6Address": ""
            },
            "d4a68577ae684e081839ee666cda5b3f03c3389f0a73be7b0a1923468d157a43": {
                "Name": "ombi",
                "EndpointID": "10072569d12eab7e0d96d0e44ab7319dd44ea21076b8c8e8d82c8ccbc1f6e654",
                "MacAddress": "02:42:ac:12:00:16",
                "IPv4Address": "172.18.0.22/16",
                "IPv6Address": ""
            },
            "de815e96d8be59ad19cf46310d5fc487d16805ce2f23e5d26d6e026c6ea17ce1": {
                "Name": "gluetun",
                "EndpointID": "dbd7a5da200058f08f2635876d1d3415d88f2c04e890c03dc8d1389bf1633a08",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "eb57d4c922267d73ad6e237a9d620d4771ea53b88e8fb3ac73b6d420456bbd42": {
                "Name": "pihole",
                "EndpointID": "3cbf9ae86c4b1b87ba8f22e7cbdae1a4fb944b83e5a1aef31576027b9717b670",
                "MacAddress": "02:42:ac:12:00:0e",
                "IPv4Address": "172.18.0.14/16",
                "IPv6Address": ""
            },
            "ef20ea198a8cf7c1dc97d0675e9f83c5a1028cc3165de32a513a7f170795a960": {
                "Name": "immich_server",
                "EndpointID": "f14b677e8b4f45f8f5fb27af0d91e0f534d83fc7409cfe0cd4835de9fc0c4c0d",
                "MacAddress": "02:42:ac:12:00:15",
                "IPv4Address": "172.18.0.21/16",
                "IPv6Address": ""
            },
            "f8be433a33e22797a207e2db1103e32957e07b7f284e9f46e6a0232f2d2eb061": {
                "Name": "paperless-gotenberg-1",
                "EndpointID": "08fb714ebfc93f818f0f003c2f0282d0d48b185715b9a820971bd0e75087d7f8",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },
            "fba4bcef0bd37923ce0f6bea5db3e3e995e818a6da5da22958b5327191683012": {
                "Name": "caddy",
                "EndpointID": "bbfb0a33c76ac763d8be8d21f08397d2ce1ee0a4af981385783be577473d7ceb",
                "MacAddress": "02:42:ac:12:00:17",
                "IPv4Address": "172.18.0.23/16",
                "IPv6Address": ""
            },
            "fff56b58bfe9e20c046df3ec18628b6aef84162292cccc662c3d25ba8f10895c": {
                "Name": "paperless-pgadmin-1",
                "EndpointID": "20592481028f7621c247f67680f544c3c2e9444827241d98eaacc8919de0c95c",
                "MacAddress": "02:42:ac:12:00:0f",
                "IPv4Address": "172.18.0.15/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]

**Comment by bohregard** [comment]
I have this same problem. In my case the docker network was created outside of docker compose using the `docker network create` command. This network is shared between compose files.

![image](https://github.com/user-attachments/assets/a3efef79-96f1-494c-be2d-454dec69073f)


I've also noted that the networks tab only shows 1 network for a given container instead of all the networks it may have. In my case, the `traefik` container is connected to 2 networks:
```
  traefik:
    image: traefik:latest
    container_name: traefik
    entrypoint: ["/bin/sh", "-c", "/etc/traefik/entrypoint.sh"]
    networks:
      default:
      proxy:
```

![image](https://github.com/user-attachments/assets/16834172-0df0-4b52-ab6e-a760e269b471)

**Comment by cblt2l** [comment]
I am experiencing the same behavior as OP on Komodo v1.16.0

In my case the network is used for a reverse proxy and was created with the Docker CLI.

`docker network create caddy_reverse_proxy`

Shows up as:

![image](https://github.com/user-attachments/assets/35cd5f5e-af38-4a5f-8c46-4dc092b3b77b)

**Comment by mbecker20** [comment]
Thanks for the information. I'll see if I can reproduce this and figure out whats going on

**Comment by mbecker20** [comment]
Should be fixed in https://github.com/mbecker20/komodo/releases/tag/v1.16.6, let me know if any issues.

**Comment by beraj** [comment]
Thanks!  That did fix it.

The case is #154 seems to still be there where when a container used another container's network (I have one going through gluetun for example) shows a guid still, but that is probably an edge case.
