### ISSUE TITLE
Podman & Logdriver local not working (sample compose.yml doesnt work in podman)

### ISSUE THREAD

**Issue by ChrisonSimtian** [mbecker20/komodo#72]
Hey,

copy & pasted the sqlite compose from your docs on a debian podman machine and got the following error:
`Error response from daemon: container create: running container create option: invalid log driver: invalid argument`

Turns out podman only supports certain log drivers:
https://docs.podman.io/en/latest/markdown/podman-run.1.html
`Currently available options are k8s-file, journald, none, passthrough and passthrough-tty, with json-file aliased to k8s-file for scripting compatibility. (Default journald).`

Not saying that is anything you would need to fix but I think it might be worth it to put up a big fat warning in your docs to tell people they need to change their log driver to something else.

I changed mine to passthrough and your SQLite compose worked right out of the box :-)

**Comment by mbecker20** [comment]
Thanks for the feedback, I wasn't aware of this. I'll provide a podman alternative.

**Comment by ChrisonSimtian** [comment]
You're welcome 😁 I changed it to journald so that cockpit spits out logging, that might be a good default for people wanting to play around with it

**Comment by mbecker20** [comment]
Hi I added info into compose setup `compose.env`:
[https://github.com/mbecker20/komodo/blob/main/compose/compose.env#L13](https://github.com/mbecker20/komodo/blob/main/compose/compose.env#L13)
