### ISSUE TITLE
[Feature] Add auto-update image system

### ISSUE THREAD

**Issue by Nonobis** [mbecker20/komodo#73]
Hello,

Do you think you could add a system for replacing watchtower natively ?
May be on stack mode, an auto-update image options ?

thnaks

**Comment by mbecker20** [comment]
Many people ask for this, and I'd like to deliver. It's not the highest priority right now but I will consider how to fit it in to the next releases.

**Comment by mbecker20** [comment]
Hey, check it out: https://github.com/mbecker20/komodo/releases/tag/v1.16.9

**Comment by Nonobis** [comment]
Nice, i will ditch watchtower on a server end check if it's working on a few days :)
