### ISSUE TITLE
500 internal error when trying to use local compose file

### ISSUE THREAD

**Issue by thedinz** [mbecker20/komodo#76]
As discussed in discord, please see attached screenshots which show proper config and the resulting error.
<img width="875" alt="SCR-20240912-lzdh" src="https://github.com/user-attachments/assets/100b043a-cef9-4e4f-b0e9-188d89dc9c78">
<img width="286" alt="SCR-20240912-mazy" src="https://github.com/user-attachments/assets/eb7ca099-168d-4f51-866a-0f59c9be5861">
<img width="595" alt="SCR-20240912-magx" src="https://github.com/user-attachments/assets/4e3b4f72-bb97-4ca9-a914-2c56af5f6586">

**Comment by bramvdzee** [comment]
You should use internal file structures:

![image](https://github.com/user-attachments/assets/d89e002d-26b5-4b02-8c2b-9ae62f6547e3)

I bound my stack folder to /etc/komodo/test for this example

**Comment by mbecker20** [comment]
When running Periphery in a container, note that the "Run Directory" references a path _within_ the container. You can mount an additional stack folder using something like:

```
  - /your/folder:/custom/stacks
```

And change the Run Directory:

```
/custom/stacks/app-1
```
