### ISSUE TITLE
Confirming actions: click to copy doesnt work on http

### ISSUE THREAD

**Issue by drixtol** [mbecker20/komodo#78]
When testing out komodo i was having issues with manipulating resources. Click to copy fails silently in the interface, but the console shows 

Uncaught TypeError: navigator.clipboard is undefined
    onClick http://site.internal:9120/assets/index-CP4Y_AHR.js:616

From a bit of quick googling it looks like that api doesnt work unless on https. I put it behind a proxy with https and issue resolved. 

While i dont have a problem with https, it would be nice if there was 
 * an error that lets you know why it doesnt work
 * the ability to disable having to copy to confirm actions. a user setting that says 'i know what im doing, just disable the copy section' or some such would be excellent.

**Comment by mbecker20** [comment]
I can do an additional configuration KOMODO_DISABLE_CONFIRM_MENU which will down grade the menu popup to the double click confirm button.

**Comment by cantchooseaname8** [comment]
I noticed this too. All of the click to copy functions within Komodo don't seem to work for me. This includes clicking the text to copy before confirming an action, webhook copy icon, etc. It would be great to get this working. Also being able to remove the additional typing before confirming an action would be helpful. Just the double click to confirm would go a long way.

**Comment by mbecker20** [comment]
Added `KOMODO_DISABLE_CONFIRM_DIALOG` in 1.15+
