### ISSUE TITLE
[Feature] Secure Komodo-Periphery Communication

### ISSUE THREAD

**Issue by seancallaway** [mbecker20/komodo#83]
In order to more easily support connections to servers across unsecured networks--and to increase security on internal networks--the connection between Komodo and the Periphery agent should be secured with TLS.

As a user looking for a Portainer replacement, this feature would be a requirement for my adoption of the software. See original Reddit discussion [here](https://www.reddit.com/r/selfhosted/comments/1fey8wg/komodo_v1142_container_management_ui_now_supports/ln165zl/).

**Comment by mbecker20** [comment]
The Periphery agent only supports http. Currently users who require TLS can deploy Caddy or another reverse proxy to handle the TLS layer, and configure the server address in Komodo Core to point to the https address.

Supporting TLS by default for the agent connections is the next step here, and requires investigation into a self-signed certificate system.

**Comment by mbecker20** [comment]
I found this Reddit post made by Portainer CEO describing a bit about how their agent connection works. [https://www.reddit.com/r/portainer/s/Z6NSYclTVi](https://www.reddit.com/r/portainer/s/Z6NSYclTVi)

**Comment by mbecker20** [comment]
v1.15: Komodo Periphery agent now has https defaulted for new setups, and easy migration to https for existing users: https://github.com/mbecker20/komodo/releases/tag/v1.15.0

**Comment by seancallaway** [comment]
Super excited about this. Thank you!
