### ISSUE TITLE
[BUG] Docker image missing architecture declaration

### ISSUE THREAD

**Issue by loan-mgt** [mbecker20/komodo#84]
Two points here:
1. The published images for *core* and *periphery* do not specify their required architecture.
2. No ARM images are published or available.

Trying to run Docker Compose on ARM gives the following output:
```
core-1 exited with code 1
core-1       | exec ./core: exec format error
periphery-1  | exec ./periphery: exec format error
```

**Comment by mbecker20** [comment]
Hi, there is another issue open to convert the images to true multi-platform. For now, arm support is user the ":latest-aarch64" tags:

- ghcr.io/mbecker20/komodo:latest-aarch64

- ghcr.io/mbecker20/periphery:latest-aarch64

**Comment by loan-mgt** [comment]
Duplicate see #52
