### ISSUE TITLE
[Bug] Can't deploy private GitLab repos

### ISSUE THREAD

**Issue by Cirx08** [mbecker20/komodo#86]
### Issue
Unable to deploy stacks from private GitLabs repo using access tokens. But can deploy from public GitLabs repos.

### Steps:
1. Log into GitLabs and create either a project specific or global account token.
2. Log into Komodo and navigate to the Settings > Providers page.
3. Create a new item under "Git Accounts" using the account username as the username and the generated token as the token.
4. Navigate to Stacks and create a new stack.
5. Under the "Git Repo" section specify the GitLabs provider created in step 3. Specify the user account also created in step 3.
6. Specify the repo, branch and yaml file path. 
7. Save the changes and attempt to deploy the stack.

### Expected:
The stack should be deployed the same as it is using a public GitLabs repo stack using the same steps.

### Actual:
The stack fails to deploy and the user is presented with the error "Cloning into '/etc/komodo/stacks/test'... fatal: could not read Password for 'https://@{{ YOUR_REPO_DOMAIN_HERE }}': No such device or address".

### Output:
![Screenshot 2024-09-19 170411](https://github.com/user-attachments/assets/30deda53-ba29-4778-bb33-a5b45dee95c5)

![image](https://github.com/user-attachments/assets/d580be27-f6f1-4069-832e-a664a0b0d582)

**Comment by stephanrenggli** [comment]
Facing exactly the same issue. I'm on v1.15.1.

**Comment by mbecker20** [comment]
Yes, thanks for your patience, I've been meaning to check on this, and release a patch if necessary.

**Comment by mbecker20** [comment]
Hi, 1.15.3 is out and should fix this issue.

**Comment by Cirx08** [comment]
Tested and confirmed working now. Thanks @mbecker20
